#include "skashekAI/debugActions.t"
#include "skashekAI/skashekAI.t"
#include "skashekAI/announcements.t"
#include "skashekAI/sounds.t"
#include "skashekAI/general.t"
#include "skashekAI/random.t"
#include "skashekAI/printing.t"
#include "skashekAI/mockCore.t"
#include "skashekAI/nav.t"
#include "skashekAI/investigation.t"
#include "skashekAI/streaks.t"

#include "skashekAI/introState.t"
#include "skashekAI/catModeState.t"
#include "skashekAI/lurkState.t"
//#include "skashekAI/ambushState.t"
#include "skashekAI/chaseState.t"